---
##
# Configuration of docker compose.
# Link and run related images.
#

#- REST API server -#
virtuoso-api:
  image: coffeine/virtuoso-api
  environment:
    DB_HOST: postgres
  ports:
   - "8080:8080"
#  volumes:
#    - .:/usr/src/virtuoso
  links:
    - postgres

#- Database -#
postgres:
  image: postgres:9.6
  volumes:
    - local_postgres:/var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
    POSTGRES_DB: "virtuoso"
    POSTGRES_USER: "virtuoso"
    POSTGRES_PASSWORD: "virtuoso"
    PGDATA: "/var/lib/postgresql/data"
